export type BannerPreset = {
  id: string;
  name: string;
  description: string;
  gradient: string;
  accent: string;
  text: string;
  softText: string;
  pattern: "none" | "grid" | "dots" | "cross";
  frame: "none" | "border" | "browser" | "terminal";
  layout: "stack" | "split" | "center";
};

export const presets: BannerPreset[] = [
  {
    id: "vercel-stark",
    name: "Vercel Stark",
    description: "Ultra-minimal high contrast white.",
    gradient: "linear-gradient(180deg, #ffffff 0%, #fcfcfc 100%)",
    accent: "#000000",
    text: "#000000",
    softText: "#666666",
    pattern: "grid",
    frame: "border",
    layout: "split",
  },
  {
    id: "linear-noir",
    name: "Linear Noir",
    description: "Deep dark mode with subtle glowing accents.",
    gradient: "radial-gradient(ellipse at 50% -20%, #202020, #0a0a0a 80%)",
    accent: "#5e6ad2",
    text: "#ffffff",
    softText: "#888888",
    pattern: "none",
    frame: "browser",
    layout: "stack",
  },
  {
    id: "supabase-emerald",
    name: "Supabase Emerald",
    description: "Dark gray with striking neon green.",
    gradient: "linear-gradient(145deg, #1c1c1c 0%, #111111 100%)",
    accent: "#3ecf8e",
    text: "#ffffff",
    softText: "#878787",
    pattern: "dots",
    frame: "none",
    layout: "split",
  },
  {
    id: "stripe-mesh",
    name: "Stripe Mesh",
    description: "Clean white with a vibrant mesh blur.",
    gradient: "radial-gradient(ellipse at top left, #f3ebff, transparent 50%), radial-gradient(ellipse at bottom right, #e0f2fe, transparent 50%), #ffffff",
    accent: "#635bff",
    text: "#0a2540",
    softText: "#425466",
    pattern: "cross",
    frame: "browser",
    layout: "center",
  },
  {
    id: "raycast-red",
    name: "Raycast Red",
    description: "Sharp focus, deep red highlights on dark.",
    gradient: "linear-gradient(180deg, #111111 0%, #000000 100%)",
    accent: "#ff6363",
    text: "#f5f5f5",
    softText: "#999999",
    pattern: "cross",
    frame: "terminal",
    layout: "stack",
  },
  {
    id: "geist-mono",
    name: "Geist Mono",
    description: "Brutalist grayscale.",
    gradient: "linear-gradient(90deg, #fafafa 0%, #ebebeb 100%)",
    accent: "#111111",
    text: "#000000",
    softText: "#777777",
    pattern: "grid",
    frame: "none",
    layout: "center",
  },
  {
    id: "sunset-blaze",
    name: "Sunset Blaze",
    description: "Vibrant and energetic orange to magenta gradient.",
    gradient: "linear-gradient(135deg, #ff9a9e 0%, #fecfef 99%, #fecfef 100%)",
    accent: "#ff0844",
    text: "#333333",
    softText: "#666666",
    pattern: "grid",
    frame: "browser",
    layout: "center",
  },
  {
    id: "midnight-aurora",
    name: "Midnight Aurora",
    description: "Deep space blue with soft glowing cyan.",
    gradient: "radial-gradient(circle at 10% 20%, #041029 0%, #091c3d 100%)",
    accent: "#00d2ff",
    text: "#e0e7ff",
    softText: "#8ea4d1",
    pattern: "dots",
    frame: "terminal",
    layout: "stack",
  },
  {
    id: "glass-frost",
    name: "Glass Frost",
    description: "Airy, frosty cool blues and white.",
    gradient: "linear-gradient(120deg, #e0c3fc 0%, #8ec5fc 100%)",
    accent: "#ffffff",
    text: "#1e3a8a",
    softText: "#4338ca",
    pattern: "none",
    frame: "border",
    layout: "split",
  },
  {
    id: "hacker-green",
    name: "Hacker Green",
    description: "Retro phosphor terminal aesthetic.",
    gradient: "linear-gradient(to right, #000000 0%, #051405 100%)",
    accent: "#00ff00",
    text: "#00ff00",
    softText: "#008800",
    pattern: "cross",
    frame: "terminal",
    layout: "center",
  },
  {
    id: "notion-minimal",
    name: "Notion Minimal",
    description: "Stark document style with crisp typography.",
    gradient: "linear-gradient(to right, #ffffff 0%, #ffffff 100%)",
    accent: "#000000",
    text: "#000000",
    softText: "#808080",
    pattern: "none",
    frame: "none",
    layout: "stack",
  },
  {
    id: "cyberpunk-neon",
    name: "Cyberpunk Neon",
    description: "Aggressive neon accents on pure void.",
    gradient: "linear-gradient(135deg, #000000 0%, #080808 100%)",
    accent: "#ff00ff",
    text: "#00ffff",
    softText: "#888888",
    pattern: "grid",
    frame: "border",
    layout: "split",
  },
  {
    id: "figma-blueprint",
    name: "Figma Blueprint",
    description: "Graph paper aesthetic with bounding box blue.",
    gradient: "linear-gradient(180deg, #f5f5f5 0%, #ececec 100%)",
    accent: "#0ea5e9",
    text: "#171717",
    softText: "#737373",
    pattern: "grid",
    frame: "browser",
    layout: "center",
  },
  {
    id: "retro-os",
    name: "Retro OS",
    description: "90s computer beige with sharp system fonts.",
    gradient: "linear-gradient(180deg, #c0c0c0 0%, #a0a0a0 100%)",
    accent: "#000080",
    text: "#000000",
    softText: "#404040",
    pattern: "dots",
    frame: "browser",
    layout: "split",
  },
  {
    id: "amethyst-glow",
    name: "Amethyst Glow",
    description: "Rich luxury violet with subtle depth.",
    gradient: "radial-gradient(circle at top right, #3b0764 0%, #1e1b4b 100%)",
    accent: "#d8b4fe",
    text: "#fafafa",
    softText: "#a78bfa",
    pattern: "none",
    frame: "none",
    layout: "center",
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    description: "Developer IDE aesthetic with slate muted tones.",
    gradient: "linear-gradient(145deg, #1a1b26 0%, #16161e 100%)",
    accent: "#7aa2f7",
    text: "#c0caf5",
    softText: "#565f89",
    pattern: "cross",
    frame: "terminal",
    layout: "stack",
  }
];
